# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  #Box Settings
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.define "vm-peer2"


    # Provider Settings
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.cpus = 4
    end

  # Network Settings
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.network :forwarded_port, guest: 4001, host: 4002
  config.vm.network :forwarded_port, guest: 5001, host: 5002, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8080, host: 8081

  config.vm.network :forwarded_port, guest: 8000, host: 8001
  config.vm.network :forwarded_port, guest: 8545, host: 8546
  # config.vm.network "public_network"

  # Folder Settings
  # config.vm.synced_folder ".", "/var/www/html", :nfs => {:mount_options => ["dmode=777", "fmode=666"]}
  config.vm.synced_folder "../setup", "/var/local", :nfs => {:mount_options => ["dmode=777", "fmode=666"]}




  # Provision Settings
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  config.vm.provision "shell", path: "../setup/bootstrap-ipfs.sh"

  VAGRANT_COMMAND = ARGV[0]
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'peer2'
  end
end

